ALTER TABLE deals
ADD COLUMN IF NOT EXISTS product_unit TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS product_size TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS product_processing_type TEXT NOT NULL DEFAULT '';

ALTER TABLE deal_projections
ADD COLUMN IF NOT EXISTS product_unit TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS product_size TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS product_processing_type TEXT NOT NULL DEFAULT '';

ALTER TABLE deal_winner_selections
ADD COLUMN IF NOT EXISTS product_unit TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS product_size TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS product_processing_type TEXT NOT NULL DEFAULT '';
