package deal

import "errors"

var (
	// Ошибки валидации
	ErrDealIDRequired        = errors.New("deal: ID is required")
	ErrCustomerIDRequired    = errors.New("deal: customer ID is required")
	ErrSupplierIDRequired    = errors.New("deal: supplier ID is required")
	ErrSellerCompanyRequired = errors.New("deal: seller company ID is required")
	ErrWinnerCompanyRequired = errors.New("deal: winner company ID is required")
	ErrAuctionIDRequired     = errors.New("deal: auction ID is required for auction deals")
	ErrQuantityPositive      = errors.New("deal: quantity must be positive")
	ErrUnitPricePositive     = errors.New("deal: unit price must be positive")
	ErrPriceMustBePositive   = errors.New("deal: price must be positive")
	ErrFinalPricePositive    = errors.New("deal: final price must be positive")
	ErrProductNameRequired   = errors.New("deal: product name is required")
	ErrCreatedAtRequired     = errors.New("deal: created at time is required")
	ErrSnapshotMissingFields = errors.New("deal: product snapshot missing required fields")

	// Ошибки состояния
	ErrCannotConfirmDeal        = errors.New("deal: cannot confirm deal in current status")
	ErrCannotPrepareContract    = errors.New("deal: cannot prepare contract in current status")
	ErrContractAlreadyPrepared  = errors.New("deal: contract already prepared")
	ErrCannotSignContract       = errors.New("deal: cannot sign contract in current status")
	ErrContractAlreadySigned    = errors.New("deal: contract already signed")
	ErrContractNumberRequired   = errors.New("deal: contract number is required")
	ErrCannotRequestPayment     = errors.New("deal: cannot request payment in current status")
	ErrPaymentAlreadyRequested  = errors.New("deal: payment already requested")
	ErrCannotMarkAsPaid         = errors.New("deal: cannot mark as paid in current status")
	ErrCannotRequestShipment    = errors.New("deal: cannot request shipment in current status")
	ErrShipmentAlreadyRequested = errors.New("deal: shipment already requested")
	ErrCannotMarkAsShipped      = errors.New("deal: cannot mark as shipped in current status")
	ErrCannotCompleteDeal       = errors.New("deal: cannot complete deal in current status")
	ErrCannotCancelDeal         = errors.New("deal: cannot cancel deal in current status")
	ErrCannotDeclineWinnerAfterConfirm = errors.New("deal: winner can only forfeit before deal is confirmed")
	ErrWinnerForfeitOnlyAuction        = errors.New("deal: winner deposit forfeit applies only to auction deals")
	ErrDealNotCancelledForFallback     = errors.New("deal: current deal must be cancelled before advancing winner selection")
	ErrWrongSelectedCandidate          = errors.New("deal: company is not the current selected winner candidate")
	ErrStaleWinnerSelection            = errors.New("deal: winner selection does not match this deal or auction state")
	ErrWinnerSelectionNotActive        = errors.New("deal: winner selection is not active")
	ErrNoAvailableWinnerCandidate      = errors.New("deal: no current winner candidate in selection")
	ErrWinnerFallbackOnlyWhileActive        = errors.New("deal: winner fallback is only allowed while selection is active")
	ErrWinnerSelectionMissingForAuctionDeal = errors.New("deal: winner selection is required to confirm an auction deal")
	ErrWinnerSelectionNotAwaitingPayment      = errors.New("deal: winner selection is not awaiting payment finalization")
	ErrWinnerSelectionDealMismatch            = errors.New("deal: winner selection deal id does not match")
	ErrDealInvoicePaidInvariant             = errors.New("deal: invoice paid payload does not match deal totals")
	ErrDealCancelledPayment                 = errors.New("deal: cannot finalize payment for cancelled deal")
	ErrCannotUpdatePrice        = errors.New("deal: cannot update price in current status")
	ErrInvalidStageTransition   = errors.New("deal: invalid stage transition")

	// Ошибки контракта
	ErrContractNotPrepared = errors.New("deal: contract not prepared")
	ErrContractNotSigned   = errors.New("deal: contract not signed")

	ErrProjectionRequired  = errors.New("deal: projection is required")
	ErrProjectionNotActive = errors.New("deal: projection is not active")
	ErrProjectionNotFound  = errors.New("deal: projection not found")
	ErrSelectionNotFound   = errors.New("deal: winner selection not found")

	ErrConfirmationRequired        = errors.New("deal: confirmation is required")
	ErrConfirmationIDRequired      = errors.New("deal: confirmation ID is required")
	ErrConfirmationDealIDRequired  = errors.New("deal: confirmation deal ID is required")
	ErrConfirmationStageRequired   = errors.New("deal: confirmation stage is required")
	ErrConfirmationStatusRequired  = errors.New("deal: confirmation status is required")
	ErrVerificationMethodRequired  = errors.New("deal: verification method is required")
	ErrRequestedAtRequired         = errors.New("deal: requested at is required")
	ErrRequestedByUserRequired     = errors.New("deal: requested by user ID is required")
	ErrRequestedByCompanyRequired  = errors.New("deal: requested by company ID is required")
	ErrCounterpartyCompanyRequired = errors.New("deal: counterparty company ID is required")
	ErrConfirmationNotFound        = errors.New("deal: confirmation not found")
	ErrConfirmationAlreadyPending  = errors.New("deal: confirmation already pending")
	ErrConfirmationNotPending      = errors.New("deal: confirmation is not pending")
	ErrConfirmationExpired         = errors.New("deal: confirmation expired")
	ErrConfirmationNotApproved     = errors.New("deal: confirmation is not approved")
	ErrConfirmationDealMismatch    = errors.New("deal: confirmation does not belong to deal")
	ErrCounterpartyRequired        = errors.New("deal: counterparty approval is required")
	ErrNotDealParticipant          = errors.New("deal: company is not a deal participant")

	// Удаленные ошибки
	// ErrOnlyDraftCanBeCompleted    = errors.New("deal: only draft deals can be completed from auction")
	// ErrDraftDealRequired          = errors.New("deal: draft deal is required")
)
